############################################################
#
# 配置数据源,使用阿里的 druid 数据源
#
############################################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1  # 初始化时,建立物理连接的数量
      min-idle: 1  # 最小连接池数量
      max-active: 20  # 最大连接池数量
      test-on-borrow: true  # 创建连接时,检测连接是否有效
      stat-view-servlet:  # 连接监控
        allow: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  logging:
    config: classpath:log4j2.yml

############################################################
#
# mybatis 配置
#
############################################################
# mybatis 配置
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
      use-generated-keys: true  # 用于主键自增的数据库中返回插入数据后的主键
      use-column-label: true  # 声明可以使用列标签（数据库字段名）代替列名（查询时的别名）
      map-underscore-to-camel-case: true  # 开启驼峰命名转换功能（user_name--userName）
# 通用 Mapper 配置
mapper:
  mappers: com.example.utils.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helper-dialect: MYSQL
  reasonable: true
  support-methods-arguments: true
  params: count,countSql
